package view.client;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebServiceClient(wsdlLocation="http://localhost:7101/NotifMundial-ViewController-context-root/FileTransfererImplService?WSDL",
  targetNamespace="http://view/", name="FileTransfererImplService")
public class FileTransfererImplService
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("view.client.FileTransfererImplService");
      URL baseUrl = FileTransfererImplService.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            FileTransfererImplService.class.getResource("http://localhost:7101/NotifMundial-ViewController-context-root/FileTransfererImplService?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://localhost:7101/NotifMundial-ViewController-context-root/FileTransfererImplService?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://localhost:7101/NotifMundial-ViewController-context-root/FileTransfererImplService?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://localhost:7101/NotifMundial-ViewController-context-root/FileTransfererImplService?WSDL",
          e);
    }
  }

  public FileTransfererImplService()
  {
    super(wsdlLocationURL,
          new QName("http://view/", "FileTransfererImplService"));
  }

  public FileTransfererImplService(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="FileTransfererImplPort")
  public view.client.FileTransfererImpl getFileTransfererImplPort()
  {
    return (view.client.FileTransfererImpl) super.getPort(new QName("http://view/",
                                                                    "FileTransfererImplPort"),
                                                          view.client.FileTransfererImpl.class);
  }

  @WebEndpoint(name="FileTransfererImplPort")
  public view.client.FileTransfererImpl getFileTransfererImplPort(WebServiceFeature... features)
  {
    return (view.client.FileTransfererImpl) super.getPort(new QName("http://view/",
                                                                    "FileTransfererImplPort"),
                                                          view.client.FileTransfererImpl.class,
                                                          features);
  }
}
